# Maven
#my new
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool: newpool

steps:
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'azure-aws'
    regionName: 'ap-south-1'
    scriptType: 'inline'
    inlineScript: |
      #! /bin/bash
      sudo ssh ec2-user@13.126.30.182
      sudo mkdir -p /git/newdir/
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
